[package]
name = "celeriant_wal"
description = "Internal: write-ahead log data structures for the Celeriant event store"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
small-metablock = []

[dependencies]
bincode.workspace = true
serde.workspace = true
serde_bytes.workspace = true
serde_json.workspace = true
deepsize.workspace = true
uuid.workspace = true
xxhash-rust.workspace = true