[package]
name = "eventplanedb_access"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
core_affinity.workspace = true
crossbeam.workspace = true
ahash.workspace = true
tokio.workspace = true
nanoid.workspace = true
tempfile.workspace = true
eventplanedb_storage = { path = "../eventplanedb_storage" }
rand.workspace = true
futures.workspace = true
serde.workspace = true
chrono.workspace = true
tikv-jemallocator = { workspace = true, optional = true }
rsa.workspace = true
sha2.workspace = true
base64.workspace = true
thiserror.workspace = true
serde_json.workspace = true

[dev-dependencies]
rand.workspace = true
nanoid.workspace = true
tempfile.workspace = true
criterion.workspace = true

