[package]
name = "celeriant_watch"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
celeriant_msg = { path = "../celeriant_msg" }
celeriant_wire = { path = "../celeriant_wire" }
celeriant_wal = { path = "../celeriant_wal" }
glommio.workspace = true

[dev-dependencies]
tempfile.workspace = true
uuid.workspace = true
criterion.workspace = true
num_cpus.workspace = true
rand.workspace = true
futures-lite.workspace = true