use std::path::Path;
use serde::{Deserialize, Serialize};

#[derive(Debug)]
pub enum ApiKeysError {
    Io(std::io::Error),
    Parse(toml::de::Error),
    InvalidHash(String),
}

impl std::fmt::Display for ApiKeysError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(e) => write!(f, "Failed to read api_keys.toml: {}", e),
            Self::Parse(e) => write!(f, "Failed to parse api_keys.toml: {}", e),
            Self::InvalidHash(msg) => write!(f, "Invalid hash format in api_keys.toml: {}", msg),
        }
    }
}

impl std::error::Error for ApiKeysError {}

impl From<std::io::Error> for ApiKeysError {
    fn from(e: std::io::Error) -> Self {
        Self::Io(e)
    }
}

impl From<toml::de::Error> for ApiKeysError {
    fn from(e: toml::de::Error) -> Self {
        Self::Parse(e)
    }
}

/// The raw TOML structure for api_keys.toml
#[derive(Debug, Deserialize, Serialize)]
pub struct ApiKeysToml {
    pub keys: KeysSection,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct KeysSection {
    pub primary_rw: String,
    pub secondary_rw: String,
    pub primary_ro: String,
    pub secondary_ro: String,
}

/// Parsed API key hashes ready for use
pub struct ApiKeysConfig {
    pub primary_rw: [u8; 32],
    pub secondary_rw: [u8; 32],
    pub primary_ro: [u8; 32],
    pub secondary_ro: [u8; 32],
}

/// Load API key hashes from api_keys.toml if it exists.
/// Returns Ok(None) if the file doesn't exist (no auth configured).
pub fn load_api_keys(data_root: &Path) -> Result<Option<ApiKeysConfig>, ApiKeysError> {
    let path = data_root.join("api_keys.toml");

    if !path.exists() {
        return Ok(None);
    }

    let content = std::fs::read_to_string(&path)?;
    let toml_config: ApiKeysToml = toml::from_str(&content)?;

    Ok(Some(ApiKeysConfig {
        primary_rw: parse_hex_hash(&toml_config.keys.primary_rw, "primary_rw")?,
        secondary_rw: parse_hex_hash(&toml_config.keys.secondary_rw, "secondary_rw")?,
        primary_ro: parse_hex_hash(&toml_config.keys.primary_ro, "primary_ro")?,
        secondary_ro: parse_hex_hash(&toml_config.keys.secondary_ro, "secondary_ro")?,
    }))
}

/// Parse a 64-character hex string into a 32-byte array (SHA-256 hash)
pub fn parse_hex_hash(hex: &str, field_name: &str) -> Result<[u8; 32], ApiKeysError> {
    if hex.len() != 64 {
        return Err(ApiKeysError::InvalidHash(format!(
            "{}: expected 64 hex characters, got {}",
            field_name,
            hex.len()
        )));
    }

    let mut hash = [0u8; 32];
    for i in 0..32 {
        let byte_hex = &hex[i * 2..i * 2 + 2];
        hash[i] = u8::from_str_radix(byte_hex, 16).map_err(|_| {
            ApiKeysError::InvalidHash(format!(
                "{}: invalid hex character in '{}'",
                field_name, byte_hex
            ))
        })?;
    }

    Ok(hash)
}

/// Convert a 32-byte hash to a 64-character hex string
fn hash_to_hex(hash: &[u8; 32]) -> String {
    hash.iter()
        .map(|b| format!("{:02x}", b))
        .collect()
}

/// Save API key hashes to api_keys.toml
pub fn save_api_keys(data_root: &Path, keys: &ApiKeysConfig) -> Result<(), ApiKeysError> {
    let path = data_root.join("api_keys.toml");

    let toml_config = ApiKeysToml {
        keys: KeysSection {
            primary_rw: hash_to_hex(&keys.primary_rw),
            secondary_rw: hash_to_hex(&keys.secondary_rw),
            primary_ro: hash_to_hex(&keys.primary_ro),
            secondary_ro: hash_to_hex(&keys.secondary_ro),
        },
    };

    let toml_content = toml::to_string_pretty(&toml_config)
        .map_err(|e| ApiKeysError::Io(std::io::Error::new(
            std::io::ErrorKind::Other,
            format!("Failed to serialize TOML: {}", e)
        )))?;

    // Add header comment
    let content = format!(
        "# Celeriant API Keys\n\
         # Generated by: celeriant keys generate\n\
         # WARNING: These are SHA-256 hashes. The plaintext keys are not recoverable.\n\n{}",
        toml_content
    );

    // Write with 0o600 permissions on Unix
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        use std::io::Write;

        let mut file = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o600)
            .open(&path)?;

        file.write_all(content.as_bytes())?;
        file.sync_all()?;
    }

    #[cfg(not(unix))]
    {
        use std::io::Write;

        let mut file = std::fs::File::create(&path)?;
        file.write_all(content.as_bytes())?;
        file.sync_all()?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_hex_hash() {
        let hash = parse_hex_hash(
            "a1b2c3d4e5f6789012345678901234567890123456789012345678901234abcd",
            "test"
        ).unwrap();

        assert_eq!(hash[0], 0xa1);
        assert_eq!(hash[1], 0xb2);
        assert_eq!(hash[31], 0xcd);
    }

    #[test]
    fn test_parse_hex_hash_wrong_length() {
        let result = parse_hex_hash("abc", "test");
        assert!(result.is_err());
    }

    #[test]
    fn test_parse_hex_hash_invalid_char() {
        let result = parse_hex_hash(
            "g1b2c3d4e5f6789012345678901234567890123456789012345678901234abcd",
            "test"
        );
        assert!(result.is_err());
    }
}
