[package]
name = "celeriant_shard"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
small-metablock = [
    "celeriant_wal/small-metablock",
    "celeriant_wire/small-metablock",
    "celeriant_distributed/small-metablock",
    "celeriant_msg/small-metablock",
    "celeriant_watch/small-metablock",
    "celeriant_memcache/small-metablock",
    "celeriant_rotating_log/small-metablock",
    "celeriant_client_glommio/small-metablock",
]

[dependencies]
celeriant_distributed = { path = "../celeriant_distributed" }
celeriant_msg = { path = "../celeriant_msg" }
celeriant_wire = { path = "../celeriant_wire" }
celeriant_wal = { path = "../celeriant_wal" }
celeriant_disk = { path = "../celeriant_disk" }
celeriant_watch = { path = "../celeriant_watch" }
celeriant_memcache = { path = "../celeriant_memcache" }
celeriant_rotating_log = { path = "../celeriant_rotating_log" }
celeriant_client_glommio = { path = "../celeriant_client_glommio" }
glommio.workspace = true
futures-lite.workspace = true
fastbloom.workspace = true
crc32c.workspace = true
deepsize.workspace = true
lru.workspace = true
bytes.workspace = true
tracing.workspace = true
metrics.workspace = true
blake3.workspace = true
rustls.workspace = true
apache-avro.workspace = true
jsonschema.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
uuid.workspace = true
criterion.workspace = true
num_cpus.workspace = true

[lib]
bench = false

[[bench]]
name = "exists_benchmark"
harness = false

[[bench]]
name = "write_benchmark"
harness = false

[[bench]]
name = "aggregate_count_benchmark"
harness = false

[[bench]]
name = "bloom_size_benchmark"
harness = false