[workspace]
# In alphabetical order
members = [
    "eventplanedb_storage",
    "eventplanedb_crypto",
    "eventplanedb_access",
    "eventplanedb_thread_worker",
    "eventplanedb_server",
    "eventplanedb",
    "eventplanedb_client",
]

resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["UtilityDelta"]
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
clap = { version = "4.5.42", features = ["derive"] }
url = "2.5.4"
bincode = "2.0.1"
serde = { version = "1.0.219", features = ["derive", "rc"] }
simd-json = "0.15.1"
stl_io = "0.8.5"
image = "0.25.6"
rand = "0.8.0"
nanoid = "0.4.0"
tempfile = "3.20.0"
zstd = "0.13.3"
criterion = "0.6.0"
postcard = { version = "1.1.2", features = ["alloc"] }
core_affinity = "0.8.3"
crossbeam = "0.8.4"
ahash = "0.8.12"
tokio = { version = "1.46.0", features = ["full"] }
futures = "0.3.31"
axum = "0.8.4"
chrono = "0.4.41"
tower-http = { version = "0.6.6", features = ["cors", "compression-br", "compression-gzip", "limit"] }
rsa = { version = "0.9.8", features = ["sha2", "pem"] }
sha2 = "0.10.9"
base64 = "0.22.1"
thiserror = "2.0.12"
spki = "0.7"
serde_json = "1.0.140"
jsonwebtoken = "9.3.1"
reqwest = { version = "0.12.22", features = ["json"] }
mimalloc = "0.1.47"
axum-prometheus = "0.8.0"
tracing = "0.1.41"
uuid = { version = "1.10.0", features = ["v4"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }