[package]
name = "eventplanedb_core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
bench = ["tempfile"]

[dependencies]
eventplanedb_structures = { path = "../eventplanedb_structures" }
fastbloom.workspace = true
lru.workspace = true
glommio.workspace = true
async-trait.workspace = true
futures-lite.workspace = true
bincode.workspace = true
serde.workspace = true
log.workspace = true
walkdir.workspace = true
tempfile = { workspace = true, optional = true }
crc32c.workspace = true

[dev-dependencies]
tempfile.workspace = true
criterion.workspace = true
num_cpus.workspace = true
uuid.workspace = true

[[bench]]
name = "read_objects_benchmark"
harness = false
required-features = ["bench"]