[package]
name = "eventplanedb_core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
eventplanedb_structures = { path = "../eventplanedb_structures" }
fastbloom.workspace = true
lru.workspace = true
glommio.workspace = true
async-trait.workspace = true
futures-lite.workspace = true
bincode.workspace = true
serde.workspace = true
crc32fast.workspace = true

[dev-dependencies]
tempfile.workspace = true
criterion.workspace = true

[[bench]]
name = "read_operations_benchmark"
harness = false