use std::sync::Arc;

use eventplanedb_storage::{catchup_result::CatchupResult, event_storage_cache::EventStorageCache};
use eventplanedb_access::{access_level::AccessLevel, claims::Claims, job_error::JobError, share_links_cache::ShareLinksCache, user_access_cache::UserAccessCache};

use crate::event_notifications::EventNotifier;

pub fn handle_read_job(
    file_path: String,
    from_si: u64,
    current_user_hash: Option<String>,
    current_user_claims: Option<Claims>,
    server_time: u64,
    share_key: Option<String>,
    max_bytes: usize,
    own_events: bool,
    event_storage_cache: &mut EventStorageCache,
    share_links_cache: &mut ShareLinksCache,
    user_access_cache: &mut UserAccessCache,
    event_notifier: Option<&EventNotifier>,
) -> Result<CatchupResult, JobError> {
    let access_events = AccessLevel::require_permission(
        event_storage_cache,
        share_links_cache,
        user_access_cache,
        &file_path,
        current_user_hash.as_deref(),
        current_user_claims.as_ref().map(|c| c.sub.as_str()),
        server_time,
        AccessLevel::Viewer,
        share_key.as_deref(),
    )?;

    let user_id = current_user_claims.as_ref().map(|c| c.sub.clone()).unwrap_or(current_user_hash.unwrap());

    if access_events.len() > 0 {
        // Notify subscribers that there are new events for this file path
        if let Some(notifier) = event_notifier {
            notifier.notify(&file_path, &user_id);
        }
    }

    let mut catchup_result = event_storage_cache.read(&file_path, from_si, max_bytes, None)?;

    if !own_events {
        let cb_clone = Some(user_id.clone());
        catchup_result.event_batches.retain(|event_batch_item| event_batch_item.cb != cb_clone);
    }

    // Still need to add any access events generated on server, even though they are generated by cb
    catchup_result.event_batches.extend(access_events.into_iter().map(|f| Arc::new(f)));

    Ok(catchup_result)
}
