use std::sync::Arc;

use eventplanedb_storage::{catchup_result::CatchupResult, event_storage_cache::EventStorageCache};
use eventplanedb_access::{access_level::AccessLevel, job_error::JobError, require_permission::require_permission, share_links_cache::ShareLinksCache, user_access_cache::UserAccessCache};

use crate::{event_notifications::EventNotifier, job_context::JobContext};

pub fn handle_read_job(
    context: JobContext,
    from_server_id: u64,
    share_id: Option<u128>,
    max_bytes: usize,
    include_own_events: bool,
    event_storage_cache: &mut EventStorageCache,
    share_links_cache: &mut ShareLinksCache,
    user_access_cache: &mut UserAccessCache,
    event_notifier: Option<&EventNotifier>,
) -> Result<CatchupResult, JobError> {

    let access_events = require_permission(
        event_storage_cache,
        share_links_cache,
        user_access_cache,
        &context.file_path,
        &context.current_client_id,
        context.current_user_id.as_deref(),
        context.server_time,
        AccessLevel::Viewer,
        share_id.as_ref(),
    )?;

    if access_events.len() > 0 {
        // Notify subscribers that there are new events for this file path
        if let Some(notifier) = event_notifier {
            notifier.notify(&context.file_path, &context.current_client_id);
        }
    }

    //If include_own_events == true, set filter to None, otherwise use context.current_client_id
    let exclude_client_id_filter = if include_own_events { None } else { Some(context.current_client_id) };

    let mut catchup_result = event_storage_cache.read(
        &context.file_path, 
        from_server_id, 
        max_bytes, 
        None,
        exclude_client_id_filter
    )?;

    // Still need to add any access events generated on server, even though they are generated by cb
    // These events are wrapped in Arc as they could come from the in-memory cache or fresh from disk
    catchup_result.event_batches.extend(access_events.into_iter().map(|f| Arc::new(f)));

    Ok(catchup_result)
}
