[package]
name = "celeriant_rotating_log"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
small-metablock = ["celeriant_wal/small-metablock", "celeriant_wire/small-metablock"]

[dependencies]
celeriant_wire = { path = "../celeriant_wire" }
celeriant_wal = { path = "../celeriant_wal" }
celeriant_disk = { path = "../celeriant_disk" }
glommio.workspace = true
futures-lite.workspace = true
lru.workspace = true
fastbloom.workspace = true
metrics.workspace = true
bincode.workspace = true

[dev-dependencies]
tempfile.workspace = true
uuid.workspace = true
criterion.workspace = true
num_cpus.workspace = true