[package]
name = "eventplanedb"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
tokio.workspace = true
chrono.workspace = true
rand.workspace = true
eventplanedb_crypto = { path = "../eventplanedb_crypto" }
eventplanedb_client = { path = "../eventplanedb_client" }