[package]
name = "celeriant_distributed"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
small-metablock = ["celeriant_wal/small-metablock"]

[dependencies]
celeriant_wal = { path = "../celeriant_wal" }
bincode.workspace = true
blake3.workspace = true
tracing.workspace = true

[dev-dependencies]
celeriant_wire = { path = "../celeriant_wire" }
futures.workspace = true