[package]
name = "celeriant"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "celeriant_lib"
path = "src/lib.rs"

[[bin]]
name = "celeriant"
path = "src/main.rs"

[features]
default = []
small-metablock = [
    "celeriant_distributed/small-metablock",
    "celeriant_runtimes/small-metablock",
    "celeriant_shard/small-metablock",
]

[dependencies]
celeriant_crypto = { path = "../celeriant_crypto" }
celeriant_distributed = { path = "../celeriant_distributed" }
celeriant_runtimes = { path = "../celeriant_runtimes" }
celeriant_sidecar = { path = "../celeriant_sidecar" }
celeriant_shard = { path = "../celeriant_shard" }
celeriant_ktls = { path = "../celeriant_ktls" }
clap.workspace = true
mimalloc.workspace = true
libc.workspace = true
dotenvy.workspace = true
tracing .workspace = true
tracing-subscriber.workspace = true
glommio.workspace = true
num_cpus.workspace = true
x509-parser.workspace = true