[package]
name = "celeriant"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "celeriant_lib"
path = "src/lib.rs"

[[bin]]
name = "celeriant"
path = "src/main.rs"

[dependencies]
clap.workspace = true
mimalloc.workspace = true
libc.workspace = true
dotenvy.workspace = true
tracing .workspace = true
tracing-subscriber.workspace = true
glommio.workspace = true
