[package]
name = "celeriant_ktls"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rustls.workspace = true
rustls-pki-types.workspace = true
glommio.workspace = true
libc.workspace = true
futures-lite.workspace = true
tracing.workspace = true

[dev-dependencies]
rcgen.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
