[package]
name = "eventplanedb_server"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
eventplanedb_storage_structures = { path = "../eventplanedb_storage_structures" }
eventplanedb_storage_stateful = { path = "../eventplanedb_storage_stateful" }
eventplanedb_storage_stateless = { path = "../eventplanedb_storage_stateless" }
env_logger = "0.11.8"
fastrand = "2.3.0"
futures-lite = "2.6.1"
glommio = { path = "../glommio" }
log = "0.4.28"
lru = "0.16.1"
num_cpus = "1.17.0"
bincode.workspace = true
thiserror.workspace = true
ahash.workspace = true
mimalloc.workspace = true
serde.workspace = true
rmp-serde.workspace = true