[package]
name = "eventplanedb_server"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "eventplanedb_server"
path = "src/main.rs"

[dependencies]
core_affinity.workspace = true
crossbeam.workspace = true
ahash.workspace = true
tokio.workspace = true
nanoid.workspace = true
tempfile.workspace = true
eventplanedb_storage = { path = "../eventplanedb_storage" }
eventplanedb_crypto = { path = "../eventplanedb_crypto" }
eventplanedb_access = { path = "../eventplanedb_access" }
eventplanedb_thread_worker = { path = "../eventplanedb_thread_worker" }
rand.workspace = true
futures.workspace = true
axum.workspace = true
serde.workspace = true
chrono.workspace = true
mimalloc = { workspace = true, optional = true }
tower-http.workspace = true
rsa.workspace = true
sha2.workspace = true
base64.workspace = true
thiserror.workspace = true
spki.workspace = true
serde_json.workspace = true
simd-json.workspace = true
reqwest.workspace = true
jsonwebtoken.workspace = true
axum-prometheus.workspace = true
tracing.workspace = true
uuid.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
rand.workspace = true
nanoid.workspace = true
tempfile.workspace = true
criterion.workspace = true
axum-test = "17.3.0"

