[package]
name = "celeriant_memcache"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
celeriant_wal = { path = "../celeriant_wal" }
celeriant_distributed = { path = "../celeriant_distributed" }
celeriant_rotating_log = { path = "../celeriant_rotating_log" }
lru.workspace = true
deepsize.workspace = true