[package]
name = "celeriant_client_demo"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "batch_main"
path = "src/batch_main.rs"

[[bin]]
name = "exists_batch_main"
path = "src/exists_batch_main.rs"

[[bin]]
name = "single_main"
path = "src/single_main.rs"

[[bin]]
name = "chaos_main"
path = "src/chaos_main.rs"

[[bin]]
name = "chaos_delete_main"
path = "src/chaos_delete_main.rs"

[dependencies]
celeriant_client_tokio = { path = "../celeriant_client_tokio" }
celeriant_msg = { path = "../celeriant_msg" }
celeriant_wire = { path = "../celeriant_wire" }
celeriant_wal = { path = "../celeriant_wal" }
tokio.workspace = true
rand.workspace = true