[package]
name = "celeriant_client_demo"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
celeriant_client_tokio = { path = "../celeriant_client_tokio" }
celeriant_msg = { path = "../celeriant_msg" }
celeriant_wire = { path = "../celeriant_wire" }
celeriant_wal = { path = "../celeriant_wal" }
tokio.workspace = true