[package]
name = "eventplanedb_glommio"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
eventplanedb_storage_structures = { path = "../eventplanedb_storage_structures" }
eventplanedb_storage_stateful = { path = "../eventplanedb_storage_stateful" }
eventplanedb_storage_stateless = { path = "../eventplanedb_storage_stateless" }
bincode.workspace = true
glommio.workspace = true
ahash.workspace = true
serde.workspace = true
thiserror.workspace = true
futures-lite.workspace = true
clap.workspace = true
libc.workspace = true
serde_json.workspace = true
rmp-serde.workspace = true
rmpv.workspace = true

[dev-dependencies]
tempfile.workspace = true

[[bin]]
name = "glommio-server"
path = "src/main.rs"