[package]
name = "celeriant_msg"
description = "Request/response message types for the Celeriant wire protocol"
keywords = ["event-sourcing", "database", "eventstore", "celeriant"]
categories = ["database"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
small-metablock = ["celeriant_wal/small-metablock", "celeriant_wire/small-metablock"]

[dependencies]
celeriant_wal = { path = "../celeriant_wal", version = "0.1.2" }
celeriant_wire = { path = "../celeriant_wire", version = "0.1.2" }
bincode.workspace = true
futures-lite.workspace = true
serde.workspace = true
deepsize.workspace = true