[package]
name = "eventplanedb_client_example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "eventplanedb_client_example"
path = "src/main.rs"

[dependencies]
eventplanedb_client = { path = "../eventplanedb_client" }
eventplanedb_structures = { path = "../eventplanedb_structures" }
tokio = { version = "1.48.0", features = ["full"]}
chrono.workspace = true