[package]
name = "celeriant_runtimes"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
small-metablock = [
    "celeriant_wal/small-metablock",
    "celeriant_shard/small-metablock",
    "celeriant_msg/small-metablock",
    "celeriant_wire/small-metablock",
    "celeriant_watch/small-metablock",
    "celeriant_distributed/small-metablock",
]

[dev-dependencies]
celeriant_rotating_log = { path = "../celeriant_rotating_log" }

[dependencies]
celeriant_crypto = { path = "../celeriant_crypto" }
celeriant_disk = { path = "../celeriant_disk" }
celeriant_shard = { path = "../celeriant_shard" }
celeriant_sidecar = { path = "../celeriant_sidecar" }
celeriant_wal = { path = "../celeriant_wal" }
celeriant_msg = { path = "../celeriant_msg" }
celeriant_wire = { path = "../celeriant_wire" }
celeriant_watch = { path = "../celeriant_watch" }
celeriant_distributed = { path = "../celeriant_distributed" }
celeriant_ktls = { path = "../celeriant_ktls" }
futures-lite.workspace = true
glommio.workspace = true
libc.workspace = true
tracing.workspace = true
flume.workspace = true
bytes.workspace = true
tokio.workspace = true
signal-hook.workspace = true
async-trait.workspace = true
rustls.workspace = true
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
axum.workspace = true