pub const PROTOCOL_VERSION_V2: u32 = 2;
pub const PROTOCOL_VERSION_V3: u32 = 3;
pub const WIRE_FIXED_BODY_SIZE: usize = 1024;
pub const WIRE_HEADER_SIZE: usize = 17;
pub const SHARD_LOG_HEADER_CURRENT_VERSION: u32 = 1;
pub const METABLOCK_CURRENT_VERSION: u32 = 1;