[package]
name = "eventplanedb_storage_stateful"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
eventplanedb_structures = { path = "../eventplanedb_structures" }
eventplanedb_sync_stateless = { path = "../eventplanedb_sync_stateless" }
fastbloom.workspace = true
lru.workspace = true
async-trait.workspace = true
futures-lite.workspace = true

[dev-dependencies]
tempfile.workspace = true
