[package]
name = "celeriant_client_glommio"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
small-metablock = ["celeriant_wal/small-metablock", "celeriant_msg/small-metablock", "celeriant_wire/small-metablock"]

[dependencies]
celeriant_msg = { path = "../celeriant_msg" }
celeriant_wire = { path = "../celeriant_wire" }
celeriant_wal = { path = "../celeriant_wal" }
celeriant_ktls = { path = "../celeriant_ktls" }
glommio.workspace = true
libc.workspace = true
futures-lite.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true